/**
 
 * @module upload
 */


const ErrorResponse = require('../utils/errorResponse');
const asyncHandler = require('../middleware/async');
const AWS=require('aws-sdk')
const uuid=require('uuid/v1')
const Upload = require('../models/Upload');

const s3=new AWS.S3({
    accessKeyId:process.env.accessKeyId,
    secretAccessKey:process.env.secretAccessKey
})



// @desc      upload image to aws-s3
// @route     GET /api/v1/upload
// @access    auth user


  /**
 * upload image to aws s3 
* @typedef {Function} upload
 * @property {String} file - image to uploade 
 * @property {String} route - GET /api/v1/upload
 * @property {String} access -auth user
 */

exports.upload = asyncHandler(async (req, res, next) => {

    const key=`${req.user.id}/${uuid()}.jpeg`
    const file = req.files.file;
    
    if (!file) {
        return next(new ErrorResponse(`Please upload a file`, 400));
      }
      /**
           * params required to connect with aws
           * @typedef {Object} params
           * @property {string} Bucket -aws bucket used to upload file inside it 
           * @property {date} Expires -Image url generated url expire 
           * @property {string} key - key for aws bucket
           * @property {string} ResponseContentType -the file type to uploade is image/png
           */
       const params = {
        Bucket: 'upload-image-1', 
        Key: key, 
        Expires: 60, 
        ResponseContentType: 'image/png'
      };



      
      s3.getSignedUrl('getObject', params, async (err, url) =>{
        if (url) {
           //save to data base 
           const file = await Upload.create({url,key});
          /**
           * response when upload image 
           * @typedef {Object} image
           * @property {string} id -Image Id in mongo db data base 
           * @property {string} url -Image url generated by aws 
           * @property {string} key -key will used with front end 
           */
        res.status(201).json({
                success: true,
                // data: {url,key},
                file
              })}
        else {return next(new ErrorResponse(err, 400))}
      }
      );



  });